version: 2
project_name: axoflow-otel-collector-releases
env:
  - COSIGN_YES=true
  - LD_FLAGS=-s -w
  - CGO_ENABLED=0
  - BUILD_FLAGS=-trimpath
release:
  replace_existing_artifacts: true
msi:
  - id: axoflow-otel-collector
    name: axoflow-otel-collector_{{ .Version }}_{{ .Os }}_{{ .MsiArch }}
    wxs: windows-installer.wxs
    extra_files:
      - axoflow.ico
      - README_windows.md
      - windows_config.yaml
      - etw_library_license.txt
builds:
  - id: axoflow-otel-collector-linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: axoflow-otel-collector
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: axoflow-otel-collector-windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: axoflow-otel-collector
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
archives:
  - id: axoflow-otel-collector
    builds:
      - axoflow-otel-collector-linux
      - axoflow-otel-collector-windows
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    files:
      - src: README_{{.Os}}.md
nfpms:
  - package_name: axoflow-otel-collector
    contents:
      - src: axoflow-otel-collector.service
        dst: /lib/systemd/system/axoflow-otel-collector.service
      - src: axoflow-otel-collector.conf
        dst: /etc/axoflow-otel-collector/axoflow-otel-collector.conf
        type: config|noreplace
      - src: linux_config.yaml
        dst: /etc/axoflow-otel-collector/config.yaml
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: axoflow-otel-collector
    builds:
      - axoflow-otel-collector-linux
    formats:
      - deb
      - rpm
    maintainer: The Axoflow Otel-Collector maintainers <support@axoflow.com>
    description: OpenTelemetry Collector - axoflow-otel-collector
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_axoflow-otel-collector_checksums.txt'
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}-amd64
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest-amd64
    extra_files:
      - linux_config.yaml
      - etw_library_license.txt
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}-arm64
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest-arm64
    extra_files:
      - linux_config.yaml
      - etw_library_license.txt
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}
    image_templates:
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}-amd64
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}-arm64
  - name_template: ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest
    image_templates:
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest-amd64
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest-arm64
signs:
  - id: cosign
    cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
  - id: msi-code-sign
    cmd: sh
    args:
      - -c
      - |2-
        osslsigncode sign \
        	-provider /usr/lib/x86_64-linux-gnu/ossl-modules/pkcs11prov.so \
        	-pkcs11module ${{ .Env.PKCS11_MODULE_PATH }} \
        	-key "pkcs11:object=${{ .Env.GCP_KEY_NAME }}" \
        	-n "Axoflow OpenTelemetry Collector" \
        	-i "https://axoflow.com" \
        	-h sha256 \
        	-t "http://timestamp.sectigo.com" \
        	-in "${artifact}" \
        	-out "${artifact}.signed" \
        	-certs ${{ .Env.CERTIFICATE_CRT_PATH }} && \
        mv "${artifact}.signed" "${artifact}"
        			
    artifacts: all
    if: '{{ eq .Os "windows" }}'
    env:
      - KMS_PKCS11_CONFIG={{ .Env.KMS_PKCS11_CONFIG }}
      - PKCS11_MODULE_PATH={{ .Env.PKCS11_MODULE_PATH }}
      - CERTIFICATE_CRT_PATH={{ .Env.CERTIFICATE_CRT_PATH }}
      - GCP_KEY_NAME={{ .Env.GCP_KEY_NAME }}
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: v
partial:
  by: target
