receivers:
  filelog/system:
    include: ['/var/log/*.log']
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0
    storage: file_storage

exporters:
  otlp/axorouter:
    endpoint: 10.0.2.2:4317
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0
    sending_queue:
      enabled: true
      storage: file_storage
    tls:
      insecure: true

  nop:

extensions:
  file_storage:
    directory: /etc/axoflow-otel-collector/storage
    create_directory: true

service:
  extensions: [file_storage]
  pipelines:
    logs/system:
      receivers: [filelog/system]
      # exporters: [otlp/axorouter]
      exporters: [nop]
  telemetry:
    metrics:
      level: basic
      readers:
        - pull:
            exporter:
              prometheus:
                host: localhost
                port: 8888
    logs:
      level: debug
      encoding: json
      initial_fields:
        service.name: axoflow-otel-collector
      # processors:
      #   - simple:
      #       exporter:
      #         otlp:
      #           protocol: grpc
      #           endpoint: 10.0.2.2:4317
      #           insecure: true
