receivers:
  filelog/system:
    include: ['/var/log/*.log']

exporters:
  otlp/axorouter:
    endpoint: 10.0.2.2:4317
    tls:
      insecure: true

  nop:

service:
  pipelines:
    logs/system:
      receivers: [filelog/system]
      #exporters: [otlp/axorouter]
      exporters: [nop]
  telemetry:
    logs:
      level: debug
      encoding: json
      initial_fields:
        service.name: axoflow-otel-collector
      processors:
        - simple:
            exporter:
              otlp:
                protocol: grpc
                endpoint: 10.0.2.2:4317
                insecure: true
