name: Package Tests

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      distribution:
        required: true
        type: string

permissions:
  contents: read

jobs:
  package-tests:
    name: Package Tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        type: ${{ fromJSON(inputs.type) }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download built artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: linux-packages

      - name: Test ${{ matrix.type }} package
        run: ./scripts/package-tests/package-tests.sh ./axoflow-otel-collector*-SNAPSHOT-*_linux_amd64.${{ matrix.type }} ${{ inputs.distribution }}
