name: Continuous Integration

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GONOSUMDB: github.com/axoflow/*
  GOPRIVATE: github.com/axoflow/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "~1.24"
          check-latest: true

      - name: Tidy go.mod files
        run: go mod tidy

      - name: Set up SSH based git operations
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Set up Deploy key for private repository access
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DEPLOY_KEY_PRIVATE_FOR_AXO_ETW }}"

      - name: Verify
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: make ci
